import type { Metadata } from "next";
import { LegalPageLayout } from "@/components/LegalPageLayout";
import { BRAND_NAME } from "@/lib/brand";

export const metadata: Metadata = {
  title: `Terms of Service — ${BRAND_NAME}`,
  description: `Terms for using the ${BRAND_NAME} fan draft game.`,
};

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms of Service">
      <p>
        <strong className="text-cream">Last updated:</strong> July 2026
      </p>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-cream">Agreement</h2>
        <p>
          By using {BRAND_NAME}, you agree to these terms. If you do not agree,
          please do not use the site.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-cream">What this is</h2>
        <p>
          {BRAND_NAME} is a free, unofficial fan game. You draft a fantasy XI
          from player ratings and compare scores with friends. It is for
          entertainment only — not gambling, betting, or fantasy sports for
          money.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-cream">No affiliation</h2>
        <p>
          {BRAND_NAME} is not affiliated with, endorsed by, or sponsored by the
          ICC, any national cricket board, franchise league, team, or player.
          Player names and statistics are used for informational and
          entertainment purposes.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-cream">Accounts and challenges</h2>
        <p>
          Signing in with Google is optional but required to create or join
          friend challenges. You are responsible for activity on your account.
          Challenge links expire 24 hours after creation. We may remove expired
          or abusive content without notice.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-cream">Acceptable use</h2>
        <p>You agree not to:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>Abuse, scrape, or overload the service or API</li>
          <li>Attempt to access other users&apos; accounts or data</li>
          <li>Use the site for unlawful purposes or to harass others</li>
          <li>Misrepresent affiliation with cricket organisations or players</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-cream">Ratings and scores</h2>
        <p>
          Player ratings and team scores are generated by our models from
          historical match data. They are approximate, may change as data is
          updated, and are not official performance measures.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-cream">Disclaimer</h2>
        <p>
          The service is provided &ldquo;as is&rdquo; without warranties. We do
          not guarantee uninterrupted access, accurate scores, or preservation of
          challenges beyond stated expiry. To the extent permitted by law, we are
          not liable for indirect or consequential damages arising from use of
          the site.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-cream">Changes</h2>
        <p>
          We may update these terms or the service at any time. Continued use
          after changes means you accept the updated terms.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-cream">Contact</h2>
        <p>
          Questions about these terms: reach the site operator through the
          contact details listed on dinerhub.in for CricExpert11.
        </p>
      </section>
    </LegalPageLayout>
  );
}
